# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
t1 = Team.create(name: 'Arizona Cardinals')
t2 = Team.create(name: 'Atlanta Falcons')
t3 = Team.create(name: 'Baltimore Ravens')
t4 = Team.create(name: 'Buffalo Bills')
t5 = Team.create(name: 'Carolina Panthers')
t6 = Team.create(name: 'Chicago Bears')
t7 = Team.create(name: 'Cincinnati Bengals')
t8 = Team.create(name: 'Cleveland Browns')
t9 = Team.create(name: 'Dallas Cowboys')
t10 = Team.create(name: 'Denver Broncos')
t11 = Team.create(name: 'Detroit Lions')
t12 = Team.create(name: 'Green Bay Packers')
t13 = Team.create(name: 'Houston Texans')
t14 = Team.create(name: 'Indianapolis Colts')
t15 = Team.create(name: 'Jacksonville Jaguars')
t16 = Team.create(name: 'Kansas City Chiefs')
t17 = Team.create(name: 'Miami Dolphins')
t18 = Team.create(name: 'Minnesota Vikings')
t19 = Team.create(name: 'New England Patriots')
t20 = Team.create(name: 'New Orleans Saints')
t21 = Team.create(name: 'New York Giants')
t22 = Team.create(name: 'New York Jets')
t23 = Team.create(name: 'Oakland Raiders')
t24 = Team.create(name: 'Philadelphia Eagles')
t25 = Team.create(name: 'Pittsburgh Steelers')
t26 = Team.create(name: 'St. Louis Rams')
t27 = Team.create(name: 'San Diego Chargers')
t28 = Team.create(name: 'San Francisco 49ers')
t29 = Team.create(name: 'Seattle Seahawks')
t30 = Team.create(name: 'Tampa Bay Buccaneers')
t31 = Team.create(name: 'Tennessee Titans')
t32 = Team.create(name: 'Washington Redskins')